<a href="https://colab.research.google.com/github/Yashwanth1565/ExceLR/blob/main/ExceLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### identifying wrong text and correcting it using textblob
from textblob import TextBlob
incorrect_text="thfge mavvn wkho is standikkng that was an elephantt"
textBlb=TextBlob(incorrect_text)
print("correct text:",textBlb.correct().string)

correct text: the man who is standing that was an elephant


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
sentences=['i love coding','i love python','coding is fun']
words=[sentence.split() for sentence in sentences]
vocabulary=sorted(set(word for sentence in words for word in sentence))
encoder=OneHotEncoder(sparse_output=False)
encoder.fit(np.array(vocabulary).reshape(-1,1))
encoded_sentences=[]
for sentence in words:
  encoded=encoder.transform(np.array(sentence).reshape(-1,1))
  encoded_sentences.append(encoded)
#print(encoded_sentences)
print("vacabulary: ",vocabulary)
for i,sentence in enumerate(encoded_sentences):
  print(f"Sentences:\n' {sentence}'")
  print("One Hot Encoding:\n",encoded_sentences[i])

vacabulary:  ['coding', 'fun', 'i', 'is', 'love', 'python']
Sentences:
' [[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]'
One Hot Encoding:
 [[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]
Sentences:
' [[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]'
One Hot Encoding:
 [[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Sentences:
' [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]'
One Hot Encoding:
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


In [ ]:
#### Bag-of-words

from sklearn.feature_extraction.text import CountVectorizer
document=["I love python programming",
          "Python programming is fun",
          "I do not love the bugs in the code"]

vectorizer=CountVectorizer()
bow_matrix=vectorizer.fit_transform(document) #### Training the data to vectorizer

vocabulary=vectorizer.get_feature_names_out()  ### gives all the unique fearures
print("Vocabulary:\n",vocabulary)
print("Bag of Words Matrix:\n",bow_matrix.toarray())


Vocabulary:
 ['bugs' 'code' 'do' 'fun' 'in' 'is' 'love' 'not' 'programming' 'python'
 'the']
Bag of Words Matrix:
 [[0 0 0 0 0 0 1 0 1 1 0]
 [0 0 0 1 0 1 0 0 1 1 0]
 [1 1 1 0 1 0 1 1 0 0 2]]


In [ ]:
### TF-IDF
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(document)
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
print(df.head())




       bugs      code        do       fun        in        is      love  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.577350   
1  0.000000  0.000000  0.000000  0.562829  0.000000  0.562829  0.000000   
2  0.323112  0.323112  0.323112  0.000000  0.323112  0.000000  0.245735   

        not  programming    python       the  
0  0.000000     0.577350  0.577350  0.000000  
1  0.000000     0.428046  0.428046  0.000000  
2  0.323112     0.000000  0.000000  0.646225  


In [ ]:
### TF-IDF
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Instead of X, use bow_matrix from the previous cell
vectorizer = TfidfVectorizer()
# Fit the vectorizer to the same documents used for bow_matrix
vectorizer.fit(document)  # Assuming 'document' is still in scope

# Transform the documents using TF-IDF
tfidf_matrix = vectorizer.transform(document)

# Create the DataFrame using tfidf_matrix
df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
print(df.head())

       bugs      code        do       fun        in        is      love  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.577350   
1  0.000000  0.000000  0.000000  0.562829  0.000000  0.562829  0.000000   
2  0.323112  0.323112  0.323112  0.000000  0.323112  0.000000  0.245735   

        not  programming    python       the  
0  0.000000     0.577350  0.577350  0.000000  
1  0.000000     0.428046  0.428046  0.000000  
2  0.323112     0.000000  0.000000  0.646225  


In [ ]:
##### Saturday 18-01-2025

In [ ]:
### NLP gram

from nltk import ngrams
from collections import Counter
sentence="I love python soo much"
text=sentence.split()
print(text)

### Creating a function

def n_gram(text,n):
  n_grams=ngrams(text,n)
  return [" ".join(grams) for grams in n_grams]



['I', 'love', 'python', 'soo', 'much']
['I', 'love', 'python', 'soo', 'much']
['I love', 'love python', 'python soo', 'soo much']
['I love python', 'love python soo', 'python soo much']


NameError: name 'quadgrams' is not defined

In [ ]:
n=1
unigrams=n_gram(text,1)
print(unigrams)
"""bigrams=n_gram(text,2)
print(bigrams)
trigrams=n_gram(text,3)
print(trigrams)
quagrams=n_gram(text,4)
print(quadgrams)"""

['I', 'love', 'python', 'soo', 'much']


'bigrams=n_gram(text,2)\nprint(bigrams)\ntrigrams=n_gram(text,3)\nprint(trigrams)\nquagrams=n_gram(text,4)\nprint(quadgrams)'

In [ ]:
'''unigrams=n_gram(text,1)
print(unigrams)'''
n=2
bigrams=n_gram(text,2)
print(bigrams)
'''trigrams=n_gram(text,3)
print(trigrams)
quagrams=n_gram(text,4)
print(quadgrams)'''


['I love', 'love python', 'python soo', 'soo much']


'trigrams=n_gram(text,3)\nprint(trigrams)\nquagrams=n_gram(text,4)\nprint(quadgrams)'

In [ ]:
'''unigrams=n_gram(text,1)
print(unigrams)
bigrams=n_gram(text,2)
print(bigrams)'''
n=3
trigrams=n_gram(text,3)
print(trigrams)
'''quagrams=n_gram(text,4)
print(quadgrams)'''

['I love python', 'love python soo', 'python soo much']


'quagrams=n_gram(text,4)\nprint(quadgrams)'

In [ ]:
''''unigrams=n_gram(text,1)
print(unigrams)
bigrams=n_gram(text,2)
print(bigrams)
trigrams=n_gram(text,3)
print(trigrams)'''
n=4
quadgrams=n_gram(text,4)
print(quadgrams)

['I love python soo', 'love python soo much']


In [ ]:
n=5
punchgrams=n_gram(text,5)
print(punchgrams)

['I love python soo much']


In [ ]:
asdfghjkl;'
456zxcvbnm,./'23qwerty7uiop[]\789+Zxcvbnm,./23


In [ ]:
!pip install gensim


In [ ]:
corpus=[
    "Ask not what your country can do for you.",
    "Change your thoughts and you change your world.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "It always seems impossible until it's done.",
    "All litters are not gold."
]

In [ ]:
corpus = [
    "The quick brown cat jumps over the lazy dog",
    "A journey of a thousand miles begins with a single step",
    "To be or not to be that is the question",
    "All that glitters is not gold",
    "The early bird catches the worm"
]

In [ ]:
tokenize_sentence=[sentence.lower().split() for sentence in corpus]
print(tokenize_sentence)

[['the', 'quick', 'brown', 'cat', 'jumps', 'over', 'the', 'lazy', 'dog'], ['a', 'journey', 'of', 'a', 'thousand', 'miles', 'begins', 'with', 'a', 'single', 'step'], ['to', 'be', 'or', 'not', 'to', 'be', 'that', 'is', 'the', 'question'], ['all', 'that', 'glitters', 'is', 'not', 'gold'], ['the', 'early', 'bird', 'catches', 'the', 'worm']]


In [ ]:
import gensim
from gensim.models import Word2Vec
model=Word2Vec(tokenize_sentence,min_count=1,vector_size=50,window=5,sg=0)
model.save("Word2Vec.model")

In [ ]:
import gensim
from gensim.models import Word2Vec # Changed word2Vec to Word2Vec
model=Word2Vec(tokenize_sentence,min_count=1,vector_size=50,window=5,sg=0) # Changed word2Vec to Word2Vec
model.save("word2Vec.model")

In [ ]:
vector=model.wv["cat"]
print(vector)

[ 1.6265802e-02 -8.9166770e-03 -2.1474273e-03  2.0087818e-03
 -3.8085945e-04  2.2845797e-03  1.2229419e-02 -3.9210954e-05
 -6.4889290e-03 -3.0246107e-03  1.1792165e-02  3.0216638e-03
 -1.4416290e-03  1.8664461e-02 -9.8503446e-03 -1.6686678e-03
  1.8349672e-02  1.3495063e-02  3.0006764e-03 -1.7775077e-02
  2.3031184e-03 -4.5672455e-03  1.8736541e-02  2.4200890e-03
  2.9817792e-03  4.8100217e-03 -3.6664247e-03 -9.9993451e-03
  4.5864380e-04 -4.0283133e-03  1.3202277e-02  1.7885761e-02
 -1.3438723e-03  5.9647011e-03 -1.2226269e-02  3.3990385e-03
 -1.3842322e-02 -1.7388793e-02 -1.1804348e-02 -1.7911090e-02
  1.4557923e-02 -1.1541561e-02  1.6557282e-02 -1.4487328e-02
  6.8516233e-03  1.9355772e-02 -1.5566316e-02 -1.9894745e-02
 -8.6559411e-03 -5.3599351e-03]


In [ ]:
similarities = model.wv.most_similar("cat")
for word,similarity in similarities:
    print(f"{word}: {similarity}")



to: 0.18995018303394318
quick: 0.18860775232315063
dog: 0.17439205944538116
or: 0.1423332542181015
lazy: 0.11533424258232117
not: 0.10170882195234299
a: 0.08100420236587524
all: 0.07590492814779282
the: 0.040798820555210114
early: 0.036736130714416504


In [ ]:
print("I going to MRU college to study NLP and they are soo good")

I going to MRU college to study NLP and they are soo good


In [1]:
import re
pattern=r"\d+"
text="oo7 is the code names for Mr.Bond"
output=re.match(pattern,text)
print(output.group())

AttributeError: 'NoneType' object has no attribute 'group'

In [23]:
import re
pattern = r"\d+"
text = "007 is the code names for Mr.Bond"
output = re.match(pattern, text)  # Changed re.match to re.search
if output:  # Check if a match was found
    print(output.group())
else:
    print("No match found.")

007


In [22]:
import re
pattern = r"\w+"
text = "hlo 007 is the code names for Mr.Bond"
output = re.match(pattern, text)  # Changed re.match to re.search
if output:  # Check if a match was found
    print(output.group())
else:
    print("No match found.")

hlo


In [29]:
import re
pattern=r"\w+"
text = "hehy 007 is the code names for Mr.Bond"
output_pattern = re.match(pattern, text)  # Changed re.match to re.search
if output_pattern:  # Check if a match was found
    print(output_pattern.group())
else:
    print("No match found.")

hehy


In [35]:
import re
pattern=r"\d+"
text = "hehy 009 is the code names 008 for Mr.Bond"
output_pattern = re.search(pattern, text)  # Changed re.match to re.search
if output_pattern:  # Check if a match was found
    print(output_pattern.group())
else:
    print("No match found.")

009


In [48]:
import re
pattern=r"\d+"
text="hehy 007 is the code names 008 for Mr.Bond"
output_pattern=re.findall(pattern,text)
print(output_pattern)

['007', '008']


In [ ]:
### There is a text with hashtags,mails and digits and i want to extract those words using NLP

In [ ]:
mails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', text)

In [50]:
import re
pattern=r"\d+"
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""
output=re.findall(pattern,text)
print(output)

['123', '1234']


In [51]:
import re
pattern=r"#\w+"
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""
output=re.findall(pattern,text)
print(output)

['#AI', '#MachineLearning']


In [54]:
import re
#pattern=r"\w+"
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""
mails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', text)
print(mails)

['info@example.com', 'support123@company.org']


In [56]:
import re
#pattern=r"\w+"
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""
mails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', text)
print(mails)

['info@example.com', 'support123@company.org']


In [71]:
import re
def extract_all(text):
    emails = re.findall(r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', text)
    hashtags = re.findall(r'#\w+', text)
    numbers = re.findall(r'\d+', text)
    clean_text = re.sub(r'\w+',' ', text)
    return emails, hashtags, numbers, clean_text
text = """
Hello world! Contact us at info@example.com or support123@company.org Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""
emails, hashtags, numbers, clean_text = extract_all(text)
print("Emails:", emails)
print("Hashtags:", hashtags)
print("Numbers:", numbers)
print("Cleaned Text:", clean_text)

Emails: ['info@example.com', 'support123@company.org']
Hashtags: ['#AI', '#MachineLearning']
Numbers: ['123', '1234']
Cleaned Text: 
   !        @ .     @ .           : #  # .
  <   =" :// . ">   </ >      .              .

